version: 2

sources:
  - name: ondrejs_dbt_integration_test_source
    tables:
      - name: test_event
        description: ''
        columns:
          - name: prop
            description: 'A test property description.'
