version: 2

sources:
  - name: web_app
    tables:
      - name: test_event
        description: '(from package 2) The test event I send.'
        columns:
          - name: prop
            description: '(from package 2) The value of the property.'
