
      - name: E
        description: 'null'
        columns:
          
      - name: D
        description: 'null'
        columns:
          
      - name: Mail Button Clicked
        description: 'null'
        columns:
          
      - name: Application Launched
        description: 'What's up?'
        columns:
          
      - name: Process Started
        description: '.Called when the process starts.'
        columns:
          
      - name: availableProcessors
        description: 'The number of available processors.
      - name: deleteMe
        description: 'null
      - name: Another Wrong User
        description: 'null'
        columns:
          
      - name: wrong-template-prop
        description: 'null
      - name: wrong_user
        description: 'null
      - name: A
        description: 'null'
        columns:
          
      - name: Snackbar Displayed
        description: 'null'
        columns:
          
      - name: length
        description: 'null
      - name: text
        description: 'null
      - name: Activity Created
        description: 'null'
        columns:
          
      - name: title
        description: 'null
      - name: Item Purchased
        description: 'Called when a user purchases an item.'
        columns:
          
      - name: revenue
        description: 'null
      - name: shippingMethod
        description: 'null
      - name: H
        description: 'null'
        columns:
          
      - name: I
        description: 'null'
        columns:
          
      - name: Options Opened
        description: 'null'
        columns:
          
      - name: F
        description: 'null'
        columns:
          
      - name: C
        description: 'null'
        columns:
          
      - name: View Loaded
        description: 'Called when a view is loaded.'
        columns:
          
      - name: name
        description: 'The view's name.
      - name: Options Item Selected
        description: 'null'
        columns:
          
      - name: title
        description: 'null
      - name: id
        description: 'null
      - name: J
        description: 'null'
        columns:
          
      - name: G
        description: 'null'
        columns:
          
      - name: B
        description: 'null'
        columns:
          